require 'highline/import'
require 'reverse_markdown'
require 'rest-client'
require 'pastel'
require 'terminal-table'
require 'active_support/inflector'
require 'active_support/configurable'

require_relative 'moviepilot/printer'
require_relative 'moviepilot/gateway'
require_relative 'moviepilot/interface'
require_relative 'moviepilot/article_builder'
require_relative 'moviepilot/article'
